require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'cosmos' do

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-simple-toast', :path => '../node_modules/react-native-simple-toast'

  target 'cosmosTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'cosmos-tvOS' do
  # Pods for cosmos-tvOS

  target 'cosmos-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
